language: java
jdk:
  - oraclejdk8
script: ant -buildfile build.xml
script: make ANT_TARGET=$ANT_TARGET test
env:
    - IDEA_VERSION=2016.3.8 ANT_TARGET=test
    - IDEA_VERSION=2017.2.7 ANT_TARGET=test
    - IDEA_VERSION=2017.3.5 ANT_TARGET=test
    - IDEA_VERSION=2018.1 ANT_TARGET=test
